.TH "sPb Directory Reference" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
sPb Directory Reference \- 
.SH SYNOPSIS
.br
.PP
.SS "Files"

.in +1c
.ti -1c
.RI "file \fBaffinity\&.cpp\fP"
.br
.ti -1c
.RI "file \fBbuildW\&.cpp\fP"
.br
.ti -1c
.RI "file \fBic\&.cpp\fP"
.br
.ti -1c
.RI "file \fBnormCut\&.cpp\fP"
.br
.ti -1c
.RI "file \fBsmatrix\&.cpp\fP"
.br
.in -1c
