.TH "Active" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Active \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBActive\fP (const double &e, const double &l, const int &p)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBActive\fP &x) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBnrg\fP"
.br
.ti -1c
.RI "double \fBlbl\fP"
.br
.ti -1c
.RI "int \fBpx\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
