.TH "Bdry_element" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Bdry_element \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBBdry_element\fP (const int &c, const int &v)"
.br
.ti -1c
.RI "\fBBdry_element\fP (const \fBBdry_element\fP &n)"
.br
.ti -1c
.RI "bool \fBoperator==\fP (const \fBBdry_element\fP &n) const "
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBBdry_element\fP &n) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "int \fBcoord\fP"
.br
.ti -1c
.RI "int \fBcc_neigh\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
