.TH "cv::ParallelInvokerUnit" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
cv::ParallelInvokerUnit \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBParallelInvokerUnit\fP (int num_bins, size_t n_ori, int r, const cv::Mat &label, const cv::Mat &gaussian_kernel)"
.br
.ti -1c
.RI "cv::Mat_< float > \fBoperator()\fP (const size_t &idx)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
