.TH "DFTconvolver" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DFTconvolver \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBDFTconvolver\fP (int num_bins, const cv::Mat &gaussian_filter)"
.br
.ti -1c
.RI "void \fBconv\fP (cv::Mat &hist)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
