.TH "Neighbor_Region" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Neighbor_Region \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBNeighbor_Region\fP (const \fBNeighbor_Region\fP &v)"
.br
.ti -1c
.RI "\fBNeighbor_Region\fP (const double &en, const double &tt, const double &bor)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBenergy\fP"
.br
.ti -1c
.RI "double \fBtotal_pb\fP"
.br
.ti -1c
.RI "double \fBbdry_length\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
