.TH "Order_node" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Order_node \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBOrder_node\fP (const double &e, const int &rregion1, const int &rregion2)"
.br
.ti -1c
.RI "bool \fBoperator<\fP (const \fBOrder_node\fP &x) const "
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "double \fBenergy\fP"
.br
.ti -1c
.RI "int \fBregion1\fP"
.br
.ti -1c
.RI "int \fBregion2\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
