.TH "Region" 3 "Thu Oct 3 2013" "My Project" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Region \- 
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBRegion\fP (const int &l)"
.br
.ti -1c
.RI "void \fBmerge\fP (\fBRegion\fP &r, int *labels, const int &label, double *ucm, const double &saliency, const int &son, const int &tx)"
.br
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "list< int > \fBelements\fP"
.br
.ti -1c
.RI "map< int, \fBNeighbor_Region\fP, 
.br
less< int > > \fBneighbors\fP"
.br
.ti -1c
.RI "list< \fBBdry_element\fP > \fBboundary\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for My Project from the source code\&.
